baseurl = "http://blog.committeeofelite.club"
copyright = "CC 4.0 CoZ Staff"
googleAnalytics = ""
paginate = 5
pygmentsStyle = "solarized-dark"
theme = "solar-theme-hugo"
title = "Committee Of Elite"

[params]
description = "Blog di CoZ" 
scheme = "preference" # light, dark, gray or preference

[menu]
[[menu.main]]
name = "Home"
url = "https://committeeofelite.club"
[[menu.main]]
name = "Feed"
url = "/index.xml"
